language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m unittest tests.itemsTest
  - python -m unittest tests.itemTest
  - python -m unittest tests.TestMumsDiscount
  - python -m unittest tests.TestStudentsDiscount